export const data = JSON.parse("{\"key\":\"v-68a24542\",\"path\":\"/others/webtools/vuepress%E7%9B%B8%E5%85%B3.html\",\"title\":\"vuepress相关\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"vuepress相关\",\"isTimeLine\":true,\"date\":\"2024-03-12T00:00:00.000Z\",\"category\":[\"webtools\"],\"tag\":[\"vuepress\"],\"description\":\"vuepress icon https://theme-hope.vuejs.press/guide/interface/icon.html#browsing-icons\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://sparksding.github.io/blogs/others/webtools/vuepress%E7%9B%B8%E5%85%B3.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"还不知道叫什么名字\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"vuepress相关\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"vuepress icon https://theme-hope.vuejs.press/guide/interface/icon.html#browsing-icons\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-03-15T08:57:47.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"还不知道叫什么名字\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"vuepress\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-03-12T00:00:00.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-03-15T08:57:47.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"vuepress相关\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-03-12T00:00:00.000Z\\\",\\\"dateModified\\\":\\\"2024-03-15T08:57:47.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"还不知道叫什么名字\\\",\\\"url\\\":\\\"https://sparksding.github.io/blogs\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"vuepress icon\",\"slug\":\"vuepress-icon\",\"link\":\"#vuepress-icon\",\"children\":[]}],\"git\":{\"createdTime\":1710493067000,\"updatedTime\":1710493067000,\"contributors\":[{\"name\":\"sparksd\",\"email\":\"sparks23332@163.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":0.07,\"words\":21},\"filePathRelative\":\"others/webtools/vuepress相关.md\",\"localizedDate\":\"2024年3月12日\",\"excerpt\":\"<h3> vuepress icon</h3>\\n<p><a href=\\\"https://theme-hope.vuejs.press/guide/interface/icon.html#browsing-icons\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://theme-hope.vuejs.press/guide/interface/icon.html#browsing-icons</a></p>\\n\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
