<template><div><hr>
<h2 id="theme-channing-cyanhighlight-atom-one-dark" tabindex="-1"><a class="header-anchor" href="#theme-channing-cyanhighlight-atom-one-dark" aria-hidden="true">#</a> theme: channing-cyan<br>
highlight: atom-one-dark</h2>
<blockquote>
<p>文章同步在公众号：萌萌哒草头将军，欢迎关注。</p>
</blockquote>
<p>今天分享几个上千⭐的库，助你玩转React学习和开发。</p>
<h2 id="🚀-react学习库" tabindex="-1"><a class="header-anchor" href="#🚀-react学习库" aria-hidden="true">#</a> 🚀 React学习库</h2>
<h3 id="💎-reactjs-interview-questions" tabindex="-1"><a class="header-anchor" href="#💎-reactjs-interview-questions" aria-hidden="true">#</a> 💎 reactjs-interview-questions</h3>
<p>git地址：<a href="https://github.com/sudheerj/reactjs-interview-questions" target="_blank" rel="noopener noreferrer">https://github.com/sudheerj/reactjs-interview-questions<ExternalLinkIcon/></a></p>
<p>内容介绍：这个仓库介绍了300+个常见的面试问题，十分详细，目前7.4k的⭐</p>
<figure><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/78133a046bc9478f8a201939ccf834ed~tplv-k3u1fbpfcp-watermark.image?" alt="image.png" tabindex="0" loading="lazy"><figcaption>image.png</figcaption></figure>
<h3 id="💎-react设计" tabindex="-1"><a class="header-anchor" href="#💎-react设计" aria-hidden="true">#</a> 💎 React设计</h3>
<p>git地址：<a href="https://github.com/SangKa/react-in-patterns-cn" target="_blank" rel="noopener noreferrer">https://github.com/SangKa/react-in-patterns-cn<ExternalLinkIcon/></a></p>
<p>内容介绍：一本完全免费的介绍React设计的电子书，目前1.2k的⭐</p>
<figure><img src="https://p3-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/e01cd7244502440d8fa99ab0659201cd~tplv-k3u1fbpfcp-watermark.image?" alt="image.png" tabindex="0" loading="lazy"><figcaption>image.png</figcaption></figure>
<h3 id="💎-react技巧" tabindex="-1"><a class="header-anchor" href="#💎-react技巧" aria-hidden="true">#</a> 💎 React技巧</h3>
<p>git地址：<a href="https://github.com/hateonion/react-bits-CN" target="_blank" rel="noopener noreferrer">https://github.com/hateonion/react-bits-CN<ExternalLinkIcon/></a></p>
<p>内容介绍：讲解React使用技巧的开源电子书，英文原版15.5k的⭐</p>
<h3 id="💎-react开发路线图" tabindex="-1"><a class="header-anchor" href="#💎-react开发路线图" aria-hidden="true">#</a> 💎 React开发路线图</h3>
<p>git地址：<a href="https://github.com/adam-golab/react-developer-roadmap/blob/master/roadmap-cn.png" target="_blank" rel="noopener noreferrer">https://github.com/adam-golab/react-developer-roadmap/blob/master/roadmap-cn.png<ExternalLinkIcon/></a></p>
<p>这个仓库罗列了一系列React开发需要学习的技能点，对于刚刚准备转码的小伙伴来说，还是十分推荐的。目前17k的⭐</p>
<figure><img src="https://p6-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/0afa17518c4f4a669bec9378315438d7~tplv-k3u1fbpfcp-watermark.image?" alt="image.png" tabindex="0" loading="lazy"><figcaption>image.png</figcaption></figure>
<h3 id="💎-react-typescript备忘录" tabindex="-1"><a class="header-anchor" href="#💎-react-typescript备忘录" aria-hidden="true">#</a> 💎 React+TypeScript备忘录</h3>
<p>git地址：<a href="https://github.com/typescript-cheatsheets/react" target="_blank" rel="noopener noreferrer">https://github.com/typescript-cheatsheets/react<ExternalLinkIcon/></a></p>
<p>内容介绍：如果你使用TypeScript开发React，那么这个仓库是值得一看的，它首先介绍了基础的ts开发介绍，另外还提供了高等进阶的一些方法，很实用，目前已经41.4k的⭐</p>
<h2 id="🚀-react工具库" tabindex="-1"><a class="header-anchor" href="#🚀-react工具库" aria-hidden="true">#</a> 🚀 React工具库</h2>
<h3 id="💎-beautiful-react-hooks" tabindex="-1"><a class="header-anchor" href="#💎-beautiful-react-hooks" aria-hidden="true">#</a> 💎 beautiful-react-hooks</h3>
<p>git地址：<a href="https://github.com/antonioru/beautiful-react-hooks" target="_blank" rel="noopener noreferrer">https://github.com/antonioru/beautiful-react-hooks<ExternalLinkIcon/></a></p>
<p>内容介绍：对React语法大刀阔斧改良的工具库，目前6.9k的⭐，语法上的改进使用起来十分舒适，其中一个状态钩子如下，如果你了解Svelte，那它的语法你肯定不会觉得陌生，和我上篇的分享不谋而合了。这仅仅是冰山一角，更多使用的工具函数可以去仓库中浏览下。</p>
<ul>
<li><a href="https://juejin.cn/post/7246777363257475129" target="_blank" rel="noopener noreferrer">🤮是时候放弃useState了，🚀这么写React更丝滑🚀<ExternalLinkIcon/></a></li>
</ul>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> <span class="token punctuation">{</span> Typography<span class="token punctuation">,</span> Space<span class="token punctuation">,</span> Button<span class="token punctuation">,</span> Tag <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'antd'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> useMutableState <span class="token keyword">from</span> <span class="token string">'beautiful-react-hooks/useMutableState'</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> <span class="token function-variable function">TestComponent</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
  <span class="token keyword">const</span> counter <span class="token operator">=</span> <span class="token function">useMutableState</span><span class="token punctuation">(</span><span class="token punctuation">{</span> <span class="token literal-property property">value</span><span class="token operator">:</span> <span class="token number">0</span> <span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

  <span class="token keyword">return</span> <span class="token punctuation">(</span>
    <span class="token operator">&lt;</span>DisplayDemo title<span class="token operator">=</span><span class="token string">"useMutableState"</span><span class="token operator">></span>
      <span class="token operator">&lt;</span>Typography<span class="token punctuation">.</span>Paragraph<span class="token operator">></span>
        <span class="token literal-property property">Counter</span><span class="token operator">:</span> <span class="token operator">&lt;</span>Tag color<span class="token operator">=</span><span class="token string">"green"</span><span class="token operator">></span><span class="token punctuation">{</span>counter<span class="token punctuation">.</span>value<span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>Tag<span class="token operator">></span>
      <span class="token operator">&lt;</span><span class="token operator">/</span>Typography<span class="token punctuation">.</span>Paragraph<span class="token operator">></span>
      <span class="token operator">&lt;</span>Space<span class="token operator">></span>
        <span class="token operator">&lt;</span>Button type<span class="token operator">=</span><span class="token string">"primary"</span> onClick<span class="token operator">=</span><span class="token punctuation">{</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> counter<span class="token punctuation">.</span>value <span class="token operator">+=</span> <span class="token number">1</span><span class="token punctuation">}</span><span class="token operator">></span>increase<span class="token operator">&lt;</span><span class="token operator">/</span>Button<span class="token operator">></span>
        <span class="token operator">&lt;</span>Button type<span class="token operator">=</span><span class="token string">"primary"</span> onClick<span class="token operator">=</span><span class="token punctuation">{</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> counter<span class="token punctuation">.</span>value <span class="token operator">-=</span> <span class="token number">1</span><span class="token punctuation">}</span><span class="token operator">></span>decrease<span class="token operator">&lt;</span><span class="token operator">/</span>Button<span class="token operator">></span>
      <span class="token operator">&lt;</span><span class="token operator">/</span>Space<span class="token operator">></span>
    <span class="token operator">&lt;</span><span class="token operator">/</span>DisplayDemo<span class="token operator">></span>
  <span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="💎-hos" tabindex="-1"><a class="header-anchor" href="#💎-hos" aria-hidden="true">#</a> 💎 hos</h3>
<p>git地址：<a href="https://github.com/deepsweet/hocs" target="_blank" rel="noopener noreferrer">https://github.com/deepsweet/hocs<ExternalLinkIcon/></a></p>
<p>内容介绍：这是一个在recompose库（React成员开发的工具库）基础上利用React高阶组件功能开发的功能库，目前已经1.9k⭐了。</p>
<p>不过这个工具库仅仅是维护阶段，不会再开发新功能了。下面是一个有趣的例子，你一定看的懂这个功能。</p>
<div class="language-javascript line-numbers-mode" data-ext="js"><pre v-pre class="language-javascript"><code><span class="token keyword">import</span> React <span class="token keyword">from</span> <span class="token string">'react'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> <span class="token punctuation">{</span> compose<span class="token punctuation">,</span> withState <span class="token punctuation">}</span> <span class="token keyword">from</span> <span class="token string">'recompose'</span><span class="token punctuation">;</span>
<span class="token keyword">import</span> withLifecycle <span class="token keyword">from</span> <span class="token string">'@hocs/with-lifecycle'</span><span class="token punctuation">;</span>

<span class="token keyword">const</span> <span class="token function-variable function">Demo</span> <span class="token operator">=</span> <span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> isLoading <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">(</span>
  <span class="token operator">&lt;</span>h1<span class="token operator">></span><span class="token punctuation">{</span> isLoading <span class="token operator">?</span> <span class="token string">'Loading'</span> <span class="token operator">:</span> <span class="token string">'Done'</span> <span class="token punctuation">}</span><span class="token operator">&lt;</span><span class="token operator">/</span>h1<span class="token operator">></span>
<span class="token punctuation">)</span><span class="token punctuation">;</span>

<span class="token keyword">export</span> <span class="token keyword">default</span> <span class="token function">compose</span><span class="token punctuation">(</span>
  <span class="token function">withState</span><span class="token punctuation">(</span><span class="token string">'isLoading'</span><span class="token punctuation">,</span> <span class="token string">'setLoading'</span><span class="token punctuation">,</span> <span class="token boolean">true</span><span class="token punctuation">)</span><span class="token punctuation">,</span>
  <span class="token function">withLifecycle</span><span class="token punctuation">(</span><span class="token punctuation">{</span>
    <span class="token function">onDidMount</span><span class="token punctuation">(</span><span class="token parameter"><span class="token punctuation">{</span> setLoading <span class="token punctuation">}</span></span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      <span class="token function">setLoading</span><span class="token punctuation">(</span><span class="token boolean">true</span><span class="token punctuation">,</span> <span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token punctuation">{</span>
        <span class="token function">setTimeout</span><span class="token punctuation">(</span><span class="token punctuation">(</span><span class="token punctuation">)</span> <span class="token operator">=></span> <span class="token function">setLoading</span><span class="token punctuation">(</span><span class="token boolean">false</span><span class="token punctuation">)</span><span class="token punctuation">,</span> <span class="token number">3000</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
      <span class="token punctuation">}</span><span class="token punctuation">)</span>
    <span class="token punctuation">}</span><span class="token punctuation">,</span>
    <span class="token function">onReceiveProps</span><span class="token punctuation">(</span><span class="token parameter">props<span class="token punctuation">,</span> nextProps</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
      console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token template-string"><span class="token template-punctuation string">`</span><span class="token string">isLoading: </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>props<span class="token punctuation">.</span>isLoading<span class="token interpolation-punctuation punctuation">}</span></span><span class="token string"> → </span><span class="token interpolation"><span class="token interpolation-punctuation punctuation">${</span>nextProps<span class="token punctuation">.</span>isLoading<span class="token interpolation-punctuation punctuation">}</span></span><span class="token template-punctuation string">`</span></span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token punctuation">}</span>
  <span class="token punctuation">}</span><span class="token punctuation">)</span>
<span class="token punctuation">)</span><span class="token punctuation">(</span>Demo<span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>类似react-use、ahooks的工具库还有很多，这里只列举了两个特别的，希望可以帮你拓宽视野。</p>
<p>今天的分享就到这了，感谢各位的观看，如果你也有值得分享的库，评论区告诉我。</p>
</div></template>


