export const data = JSON.parse("{\"key\":\"v-630ed466\",\"path\":\"/java/spring/spring-starter/spring%E6%95%B4%E5%90%88sharding-jdbc.html\",\"title\":\"spring整合sharding-jdbc\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"spring整合sharding-jdbc\",\"isTimeLine\":true,\"date\":\"2024-03-14T00:00:00.000Z\",\"category\":[\"java\"],\"tag\":[\"sharding-jdbc\",\"spring\"],\"description\":\"参考文章 Sharding-JDBC 源码之启动流程分析 ShardingJDBC源码阅读（二）创建ShardingDataSource Sharding-JDBC介绍\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://sparksding.github.io/blogs/java/spring/spring-starter/spring%E6%95%B4%E5%90%88sharding-jdbc.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"还不知道叫什么名字\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"spring整合sharding-jdbc\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"参考文章 Sharding-JDBC 源码之启动流程分析 ShardingJDBC源码阅读（二）创建ShardingDataSource Sharding-JDBC介绍\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"还不知道叫什么名字\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"sharding-jdbc\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"spring\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-03-14T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"spring整合sharding-jdbc\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-03-14T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"还不知道叫什么名字\\\",\\\"url\\\":\\\"https://sparksding.github.io/blogs\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"参考文章\",\"slug\":\"参考文章\",\"link\":\"#参考文章\",\"children\":[]}],\"git\":{\"createdTime\":null,\"updatedTime\":null,\"contributors\":[]},\"readingTime\":{\"minutes\":0.17,\"words\":52},\"filePathRelative\":\"java/spring/spring-starter/spring整合sharding-jdbc.md\",\"localizedDate\":\"2024年3月14日\",\"excerpt\":\"<h3> 参考文章</h3>\\n<p><a href=\\\"https://blog.csdn.net/smile_from_2015/article/details/111463029\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">Sharding-JDBC 源码之启动流程分析</a><br>\\n<a href=\\\"https://juejin.cn/post/6905608068420091911\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">ShardingJDBC源码阅读（二）创建ShardingDataSource</a><br>\\n<a href=\\\"https://blog.csdn.net/sinat_34814635/article/details/78465631\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">Sharding-JDBC介绍</a></p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
