export const data = JSON.parse("{\"key\":\"v-531b530a\",\"path\":\"/java/awesome-project/netty/netty%E9%AA%A8%E6%9E%B6.html\",\"title\":\"netty骨架(自己实现的netty)\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"netty骨架(自己实现的netty)\",\"isTimeLine\":true,\"date\":\"2024-03-09T00:00:00.000Z\",\"category\":[\"java\"],\"tag\":[\"netty\"],\"description\":\"netty线程模型 register时序\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://sparksding.github.io/blogs/java/awesome-project/netty/netty%E9%AA%A8%E6%9E%B6.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"还不知道叫什么名字\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"netty骨架(自己实现的netty)\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"netty线程模型 register时序\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-03-12T03:37:13.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"还不知道叫什么名字\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"netty\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-03-09T00:00:00.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-03-12T03:37:13.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"netty骨架(自己实现的netty)\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-03-09T00:00:00.000Z\\\",\\\"dateModified\\\":\\\"2024-03-12T03:37:13.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"还不知道叫什么名字\\\",\\\"url\\\":\\\"https://sparksding.github.io/blogs\\\"}]}\"]]},\"headers\":[{\"level\":3,\"title\":\"各个类的功能\",\"slug\":\"各个类的功能\",\"link\":\"#各个类的功能\",\"children\":[]},{\"level\":3,\"title\":\"Channel\",\"slug\":\"channel\",\"link\":\"#channel\",\"children\":[]},{\"level\":3,\"title\":\"参考文章\",\"slug\":\"参考文章\",\"link\":\"#参考文章\",\"children\":[]}],\"git\":{\"createdTime\":1710214633000,\"updatedTime\":1710214633000,\"contributors\":[{\"name\":\"sparksd\",\"email\":\"sparks23332@163.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":1.29,\"words\":386},\"filePathRelative\":\"java/awesome-project/netty/netty骨架.md\",\"localizedDate\":\"2024年3月9日\",\"excerpt\":\"<figure><img src=\\\"/assets/images/java/awesome-project/netty/netty_workflow.png\\\" alt=\\\"netty线程模型\\\" width=\\\"700\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>netty线程模型</figcaption></figure>\\n<figure><img src=\\\"/assets/images/java/awesome-project/netty/SingleThreadEventLoop_register.png\\\" alt=\\\"register时序\\\" width=\\\"500\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>register时序</figcaption></figure>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
