<template><div><h2 id="aop的实现" tabindex="-1"><a class="header-anchor" href="#aop的实现" aria-hidden="true">#</a> <strong>AOP的实现</strong></h2>
<h3 id="没有循环依赖的bean的aop时机" tabindex="-1"><a class="header-anchor" href="#没有循环依赖的bean的aop时机" aria-hidden="true">#</a> <strong>没有循环依赖的bean的AOP时机</strong></h3>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token keyword">abstract</span> <span class="token keyword">class</span> <span class="token class-name">AbstractAutoProxyCreator</span> <span class="token keyword">extends</span> <span class="token class-name">ProxyProcessorSupport</span>
		<span class="token keyword">implements</span> <span class="token class-name">SmartInstantiationAwareBeanPostProcessor</span><span class="token punctuation">,</span> <span class="token class-name">BeanFactoryAware</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><p>InstantiationAwareBeanPostProcessor接口中包含方法postProcessAfterInitialization</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token keyword">public</span> <span class="token class-name">Object</span> <span class="token function">postProcessAfterInitialization</span><span class="token punctuation">(</span><span class="token annotation punctuation">@Nullable</span> <span class="token class-name">Object</span> bean<span class="token punctuation">,</span> <span class="token class-name">String</span> beanName<span class="token punctuation">)</span> <span class="token punctuation">{</span>
    <span class="token keyword">if</span> <span class="token punctuation">(</span>bean <span class="token operator">!=</span> <span class="token keyword">null</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
        <span class="token comment">// 如果是普通bean，则返回beanName，如果是FactoryBean,则返回加上前缀&amp;的&amp;beanName</span>
        <span class="token class-name">Object</span> cacheKey <span class="token operator">=</span> <span class="token function">getCacheKey</span><span class="token punctuation">(</span>bean<span class="token punctuation">.</span><span class="token function">getClass</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> beanName<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token comment">// earlyProxyReferences中缓存的是已经创建好的代理对象</span>
        <span class="token keyword">if</span> <span class="token punctuation">(</span><span class="token operator">!</span><span class="token keyword">this</span><span class="token punctuation">.</span>earlyProxyReferences<span class="token punctuation">.</span><span class="token function">contains</span><span class="token punctuation">(</span>cacheKey<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
            <span class="token keyword">return</span> <span class="token function">wrapIfNecessary</span><span class="token punctuation">(</span>bean<span class="token punctuation">,</span> beanName<span class="token punctuation">,</span> cacheKey<span class="token punctuation">)</span><span class="token punctuation">;</span>
        <span class="token punctuation">}</span>
    <span class="token punctuation">}</span>
    <span class="token keyword">return</span> bean<span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="出现循环依赖的bean的aop时机" tabindex="-1"><a class="header-anchor" href="#出现循环依赖的bean的aop时机" aria-hidden="true">#</a> <strong>出现循环依赖的bean的AOP时机</strong></h3>
<p>对应<RouterLink to="/java/spring/spring%E6%89%A9%E5%B1%95%E7%82%B9.html">spring扩展点</RouterLink> (循环依赖: 提前AOP)</p>
<div class="language-java line-numbers-mode" data-ext="java"><pre v-pre class="language-java"><code><span class="token annotation punctuation">@Override</span>
<span class="token keyword">public</span> <span class="token class-name">Object</span> <span class="token function">getEarlyBeanReference</span><span class="token punctuation">(</span><span class="token class-name">Object</span> bean<span class="token punctuation">,</span> <span class="token class-name">String</span> beanName<span class="token punctuation">)</span> <span class="token punctuation">{</span>
  <span class="token class-name">Object</span> cacheKey <span class="token operator">=</span> <span class="token function">getCacheKey</span><span class="token punctuation">(</span>bean<span class="token punctuation">.</span><span class="token function">getClass</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">,</span> beanName<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">this</span><span class="token punctuation">.</span>earlyProxyReferences<span class="token punctuation">.</span><span class="token function">put</span><span class="token punctuation">(</span>cacheKey<span class="token punctuation">,</span> bean<span class="token punctuation">)</span><span class="token punctuation">;</span>
  <span class="token keyword">return</span> <span class="token function">wrapIfNecessary</span><span class="token punctuation">(</span>bean<span class="token punctuation">,</span> beanName<span class="token punctuation">,</span> cacheKey<span class="token punctuation">)</span><span class="token punctuation">;</span>
<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="杂项" tabindex="-1"><a class="header-anchor" href="#杂项" aria-hidden="true">#</a> 杂项</h3>
<p><a href="https://blog.csdn.net/JustForSS/article/details/83008824" target="_blank" rel="noopener noreferrer">spring中expose-proxy的作用与原理<ExternalLinkIcon/></a></p>
<p><a href="https://blog.csdn.net/minghao0508/article/details/125834496" target="_blank" rel="noopener noreferrer">Spring——事务注解@Transactional的源码分析<ExternalLinkIcon/></a></p>
<h3 id="参考文章" tabindex="-1"><a class="header-anchor" href="#参考文章" aria-hidden="true">#</a> 参考文章</h3>
<p><a href="https://javadoop.com/post/spring-aop-source" target="_blank" rel="noopener noreferrer">javadoop<ExternalLinkIcon/></a><br>
<a href="https://www.jianshu.com/p/e09ff92dfa8d" target="_blank" rel="noopener noreferrer">简书<ExternalLinkIcon/></a><br>
<a href="https://blog.csdn.net/wuyuwei/article/details/88319018" target="_blank" rel="noopener noreferrer">Spring AOP 最全源码详解之AOP元数据解析<ExternalLinkIcon/></a><br>
<a href="https://blog.csdn.net/wuyuwei/article/details/88357698" target="_blank" rel="noopener noreferrer">Spring AOP 最全源码详解之创建代理对象<ExternalLinkIcon/></a></p>
</div></template>


