export const data = JSON.parse("{\"key\":\"v-1a0fef8c\",\"path\":\"/java/spring/springMVC.html\",\"title\":\"spring MVC原理解析\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"spring MVC原理解析\",\"isTimeLine\":true,\"date\":\"2024-03-21T00:00:00.000Z\",\"category\":[\"java\"],\"tag\":[\"spring\",\"springMVC\"],\"description\":\"tomcat架构 http://localhost:8080/SpringMVCTest_war_exploded/app/test\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://sparksding.github.io/blogs/java/spring/springMVC.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"还不知道叫什么名字\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"spring MVC原理解析\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"tomcat架构 http://localhost:8080/SpringMVCTest_war_exploded/app/test\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"og:updated_time\",\"content\":\"2024-03-23T10:17:19.000Z\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"还不知道叫什么名字\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"spring\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"springMVC\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2024-03-21T00:00:00.000Z\"}],[\"meta\",{\"property\":\"article:modified_time\",\"content\":\"2024-03-23T10:17:19.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"spring MVC原理解析\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2024-03-21T00:00:00.000Z\\\",\\\"dateModified\\\":\\\"2024-03-23T10:17:19.000Z\\\",\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"还不知道叫什么名字\\\",\\\"url\\\":\\\"https://sparksding.github.io/blogs\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"创建流程\",\"slug\":\"创建流程\",\"link\":\"#创建流程\",\"children\":[]},{\"level\":2,\"title\":\"对应源码\",\"slug\":\"对应源码\",\"link\":\"#对应源码\",\"children\":[]},{\"level\":2,\"title\":\"SpringMVC处理请求流程\",\"slug\":\"springmvc处理请求流程\",\"link\":\"#springmvc处理请求流程\",\"children\":[{\"level\":3,\"title\":\"参考网页\",\"slug\":\"参考网页\",\"link\":\"#参考网页\",\"children\":[]}]}],\"git\":{\"createdTime\":1711189039000,\"updatedTime\":1711189039000,\"contributors\":[{\"name\":\"sparksd\",\"email\":\"sparks23332@163.com\",\"commits\":1}]},\"readingTime\":{\"minutes\":2.61,\"words\":783},\"filePathRelative\":\"java/spring/springMVC.md\",\"localizedDate\":\"2024年3月21日\",\"excerpt\":\"<figure><img src=\\\"/assets/images/java/spring/tomcat架构.png\\\" alt=\\\"tomcat架构\\\" width=\\\"600\\\" tabindex=\\\"0\\\" loading=\\\"lazy\\\"><figcaption>tomcat架构</figcaption></figure>\\n<p><a href=\\\"http://localhost:8080/SpringMVCTest_war_exploded/app/test\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">http://localhost:8080/SpringMVCTest_war_exploded/app/test</a></p>\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
